apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staffflow-ingress
  namespace: staffflow-hr
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
    - hosts:
        - app.staffflow.uz
        - api.staffflow.uz
      secretName: staffflow-tls
  rules:
    - host: app.staffflow.uz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: staffflow-web
                port:
                  number: 3000
    - host: api.staffflow.uz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: staffflow-api
                port:
                  number: 4000
